spring.application.name=foodbridge-backend

spring.datasource.url=jdbc:mysql://localhost:3306/foodbridge_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080
debug=true
jwt.secret=foodbridgeSecretKeyForJWTTokenGenerationMustBeLongEnough123456
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=foodbridge.noreplay@gmail.com
spring.mail.password=akfjapihrhbkgqir
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2


cloudinary.cloud-name=dx2dwsiph
cloudinary.api-key=723734886726516
cloudinary.api-secret=IgeBFz4NJpkUCDgA17EK_ShFK30