spring.application.name=foodbridge-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/foodbridge_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

jwt.secret=${JWT_SECRET:foodbridgeSecretKeyForJWTTokenGenerationMustBeLongEnough123456}
jwt.expiration=${JWT_EXPIRATION:86400000}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dx2dwsiph}
cloudinary.api-key=${CLOUDINARY_API_KEY:your_local_api_key}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:your_local_api_secret}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:foodbridge.noreplay@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:akfjapihrhbkgqir}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:smtp.gmail.com}

server.port=${SERVER_PORT:8080}

debug=true